[build]
builder = "DOCKERFILE"

dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'if [ -f /app/backend/package.json ]; then cd /app/backend && npm run start; elif [ -f /app/package.json ]; then npm run start; else echo \"No backend package.json found\" && exit 1; fi'"
